### PR TITLE
Update console.py

### PR DESCRIPTION
**Pull request by ImmaSB**
Added support for linux systems for the title changer

### CODE REVIEW

**Comment by ItsMeSB** [comment]
Oh extremely sorry, maybe I did a typo on that

**Comment by seadhy** [comment]
I guessi, i can't fix it here. I can accept it when i fix it and create a pull request again

**Comment by seadhy** [comment]
This is my first time getting a pull request and idk exactly how it works, i guess i cant accept it by changing myself. Can you fix the typo and open a pull request back?

**Comment by ImmaSB** [comment]
Yea, my first time as well.
Sure

**Review by ImmaSB — COMMENTED** [review]
Fixed Typo

**Pull request merged**
